// import { YoutubeTranscript } from 'youtube-transcript-plus';

// async function fetchAnyTranscript(videoId) {
//   try {
//     const yt = new YoutubeTranscript();

//     // 1. Get a list of ALL available caption tracks first
//     const metadata = await yt.listLanguages(videoId);
    
//     if (metadata.length === 0) {
//       console.log("❌ No transcripts available for this video (disabled by creator).");
//       return;
//     }

//     // 2. Pick the first available language (usually the default or auto-gen)
//     const bestLang = metadata[0].languageCode;
//     console.log(`✅ Found transcript in: ${metadata[0].languageName} (${bestLang})`);
//     console.log(`🤖 Is Auto-Generated: ${metadata[0].isAutoGenerated}`);

//     // 3. Fetch the actual text
//     const transcript = await yt.fetchTranscript(videoId, { lang: bestLang });

//     // Join the lines into a single block of text
//     const fullText = transcript.map(line => line.text).join(' ');
//     console.log("--- TRANSCRIPT START ---");
//     console.log(fullText); 
    
//     return fullText;

//   } catch (error) {
//     console.error("Critical Error:", error.message);
//   }
// }

// // Usage
// // fetchAnyTranscript('KaLKyK7LDdA');





// // import youtubedl from 'youtube-dl-exec';
// // import axios from 'axios';

// // async function getTranscriptOnly(videoUrl) {
// //     try {
// //         console.log("1. Finding transcript links...");
        
// //         const metadata = await youtubedl(videoUrl, {
// //             skipDownload: true,
// //             writeAutoSubs: true,
// //             writeSubs: true,
// //             dumpSingleJson: true,
// //             noWarnings: true,
// //         });

// //         const subs = metadata.requested_subtitles;
// //         if (!subs || Object.keys(subs).length === 0) {
// //             console.warn("⚠️ No transcripts found.");
// //             return ""; 
// //         }

// //         const langCode = subs.en ? 'en' : Object.keys(subs)[0];
// //         const transcriptUrl = subs[langCode].url;
        
// //         console.log(`2. Fetching ${langCode} transcript...`);

// //         const response = await axios.get(transcriptUrl, {
// //             headers: { 'User-Agent': 'Mozilla/5.0' }
// //         });

// //         // --- SAFETY CHECK FOR DATA FORMAT ---
// //         let cleanText = "";

// //         // Format A: JSON3 (Standard for most API calls)
// //         if (response.data && response.data.events) {
// //             cleanText = response.data.events
// //                 .filter(event => event.segs)
// //                 .map(event => event.segs.map(s => s.utf8).join(''))
// //                 .join(' ');
// //         } 
// //         // Format B: Simple XML or Plain Text (Backup)
// //         else if (typeof response.data === 'string') {
// //             // Strip XML tags if present
// //             cleanText = response.data.replace(/<[^>]*>?/gm, ' ');
// //         }
// //         // Format C: Different JSON structure
// //         else if (response.data && response.data.body && response.data.body.initial_segments) {
// //              cleanText = response.data.body.initial_segments.map(s => s.cueText).join(' ');
// //         }

// //         // Final cleanup: Remove extra spaces and newlines
// //         return cleanText.replace(/\s+/g, ' ').trim();

// //     } catch (error) {
// //         console.error("❌ Extraction Error:", error.message);
// //         return ""; // Return empty string so .substring() doesn't crash later
// //     }
// // }

// // // Usage with safety check
// // const url = 'https://www.youtube.com/watch?v=uJbbtrx5M_E';
// // getTranscriptOnly(url).then(text => {
// //     if (text) {
// //         console.log("✅ Success! Preview:");
// //         console.log(text.substring(0, 500) + "...");
// //     } else {
// //         console.log("❌ Failed to retrieve text content.");
// //     }
// // });
import {ChatOllama , OllamaEmbeddings} from "@langchain/ollama"

export const model = new ChatOllama({
  model: "mistral",
  temperature: 0,
  baseUrl: "http://localhost:11434",
  streaming: false,
});

async function check(){
    const res = await model.invoke("give me short stpory");
    console.log(res)
}

check()